import { Column, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';

/**
 * TypeORM Entity for the `service_request_history` table.
 * 
 * This class maps directly to the database table that Liquibase creates.
 * This table serves as an append-only, immutable audit log of every version
 * of every ServiceRequest resource that has ever existed in the system.
 * 
 * Unlike the main `service_request` table, this history table:
 * - Never updates existing rows (append-only)
 * - Preserves every version of every ServiceRequest resource
 * - Enables FHIR version history queries (_history endpoints)
 * - Provides complete audit trail capabilities
 */
@Entity('service_request_history')
@Index('idx_service_request_history_id', ['id'])
@Index('idx_service_request_history_txid', ['txid'])
export class ServiceRequestHistory {
    /**
     * The primary key for the history row itself.
     * This is a unique UUID for this specific historical entry and is distinct 
     * from the service request's logical ID.
     * 
     * @PrimaryGeneratedColumn('uuid') tells TypeORM that this is a primary key,
     * it's of type UUID, and it's automatically generated by the database.
     */
    @PrimaryGeneratedColumn('uuid', { name: 'history_id' })
    historyId: string;

    /**
     * The logical ID of the ServiceRequest resource this history entry belongs to.
     * This is the value that is shared with the `id` column in the `service_request` table.
     * It is the key used to retrieve all historical versions for a single service request.
     * 
     * Note: This is NOT a foreign key, to allow for deletion of the current resource 
     * while preserving history.
     */
    @Column('uuid', { name: 'id', nullable: false })
    id: string;

    /**
     * The version number of this historical state (e.g., 1, 2, 3...).
     * This allows for reconstructing the timeline of changes for a resource.
     * Each update to the ServiceRequest increments this version number.
     */
    @Column('int', { name: 'version_id', nullable: false })
    versionId: number;

    /**
     * The exact timestamp of when this historical version was created.
     * This corresponds to when the ServiceRequest was created or updated.
     */
    @Column('timestamptz', { name: 'last_updated', nullable: false })
    lastUpdated: Date;

    /**
     * The ID of the database transaction that created this historical version.
     * This provides a complete audit trail, linking this change to any other
     * resource changes that happened in the same atomic API call.
     * 
     * For example, if a Bundle transaction creates multiple resources,
     * they will all share the same txid.
     */
    @Column('uuid', { name: 'txid', nullable: false })
    txid: string;

    /**
     * The complete FHIR ServiceRequest resource as it existed at this point in time,
     * stored as a JSONB object. This contains all the service request data including:
     * - Patient and requester references
     * - Service/procedure details
     * - Status and priority
     * - Clinical reasoning
     * - All other FHIR ServiceRequest fields
     */
    @Column('jsonb', { name: 'resource', nullable: false })
    resource: object;
}

