import { Column, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';
/** TypeORM Entity for the `encounter_history` table. */
/**
 * TypeORM Entity for the `encounter_history` table.
 *
 * This class maps directly to the database table that Liquibase creates.
 * This table serves as an append-only, immutable audit log of every version
 * of every Encounter resource that has ever existed in the system.
 */
@Entity('encounter_history')
@Index('idx_encounter_history_id', ['id'])
@Index('idx_encounter_history_txid', ['txid'])
export class EncounterHistory {
    /**
     * The UUIDv4 primary key of this row in the table.
     * This column is automatically generated by Postgres.
     */
    @PrimaryGeneratedColumn('uuid', { name: 'history_id' })
    historyId: string;

    /**
     * The UUIDv4 of the `Encounter` resource that this row represents.
     * This links to the `id` column in the `encounter` table.
     */
    @Column('uuid', { name: 'id', nullable: false })
    id: string;

    /**
     * A monotonically increasing integer that represents the version of the
     * `Encounter` resource that this row represents.
     * The first version of a resource is always `1`.
     * This column is updated automatically by the `GenericFhirService` each time
     * a resource is updated.
     */
    @Column('int', { name: 'version_id', nullable: false })
    versionId: number;

    /**
     * The timestamp when this version of the resource was saved to the database.
     * This column is updated automatically by the `GenericFhirService` each time
     * a resource is saved.
     */
    @Column('timestamptz', { name: 'last_updated', nullable: false })
    lastUpdated: Date;

    /**
     * The UUIDv4 of the database transaction that saved this version of the resource.
     * This links to the `txid` column in the `fhir_audit_log` table.
     */
    @Column('uuid', { name: 'txid', nullable: false })
    txid: string;

    /**
     * The FHIR resource that this row represents.
     * This is a JSONB column that stores the resource in its wire format.
     */
    @Column('jsonb', { name: 'resource', nullable: false })
    resource: object;
}
