import { Column, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';

/**
 * TypeORM Entity for the `imaging_study_history` table.
 *
 * This class maps directly to the database table that Liquibase creates.
 * This table serves as an append-only, immutable audit log of every version
 * of every ImagingStudy resource that has ever existed in the system.
 */
@Entity('imaging_study_history')
@Index('idx_imaging_study_history_id', ['id'])
@Index('idx_imaging_study_history_txid', ['txid'])
export class ImagingStudyHistory {

    /**
     * The primary key for the history row itself.
     * This is a unique UUID for this specific historical entry and is distinct from the imaging study's logical ID.
     * @PrimaryGeneratedColumn('uuid') tells TypeORM that this is a primary key,
     * it's of type UUID, and it's automatically generated by the database.
     */
    @PrimaryGeneratedColumn('uuid', { name: 'history_id' })
    historyId: string;

    /**
     * The logical ID of the ImagingStudy resource this history entry belongs to.
     * This is the value that is shared with the `id` column in the `imaging_study` table.
     * It is the key used to retrieve all historical versions for a single imaging study.
     * Note: This is NOT a foreign key, to allow for deletion of the current resource while preserving history.
     */
    @Column('uuid', { name: 'id', nullable: false })
    id: string;

    /**
     * The version number of this historical state (e.g., 1, 2, 3...).
     * This allows for reconstructing the timeline of changes for a resource.
     */
    @Column('int', { name: 'version_id', nullable: false })
    versionId: number;

    /**
     * The exact timestamp of when this historical version was created.
     */
    @Column('timestamptz', { name: 'last_updated', nullable: false })
    lastUpdated: Date;

    /**
     * The ID of the database transaction that created this historical version.
     * This provides a complete audit trail, linking this change to any other
     * resource changes that happened in the same atomic API call.
     */
    @Column('uuid', { name: 'txid', nullable: false })
    txid: string;

    /**
     * The complete FHIR ImagingStudy resource as it existed at this point in time,
     * stored as a JSONB object.
     */
    @Column('jsonb', { name: 'resource', nullable: false })
    resource: object;

}
