import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/**
 * TypeORM Entity for the `fhir_search_params` table.
 * 
 * This class defines the structure of our search metadata. Each instance of this
 * class corresponds to a single row in the `fhir_search_params` table, representing
 * one valid, searchable parameter for a specific FHIR resource.
 */
@Entity('fhir_search_params')
export class FhirSearchParameter {

  /**
   * The primary key for the table.
   * @PrimaryGeneratedColumn('uuid') tells TypeORM that this is a primary key,
   * it's of type UUID, and it's automatically generated by the database (thanks to the
   * uuid-ossp extension in our schema.sql).
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * The FHIR resource this search parameter applies to (e.g., 'Patient', 'Observation').
   * @Column() marks this as a standard database column.
   */
  @Column({ name: 'resource_type' })
  resourceType: string;

  /**
   * The name of the search parameter as used in the URL query string (e.g., 'birthdate', 'gender').
   */
  @Column()
  name: string;

  /**
   * The FHIR-defined search parameter type ('string', 'date', 'token', 'reference', 'number').
   * This is crucial because it tells our GenericSearchService which logic "handler" to use
   * for building the SQL query (e.g., date logic handles prefixes like 'gt', 'lt').
   */
  @Column()
  type: string;

  /**
   * The heart of the data-driven engine. This field contains the SQL expression
   * used to access the searchable data within the resource's JSONB column.
   * Example: For a 'birthdate' search, the expression would be `resource ->> 'birthDate'`.
   * For an '_id' search, it points to the table's primary key: `patient.id`.
   */
  @Column()
  expression: string;

  /**
   * A human-readable description of the parameter.
   * This is used to dynamically generate the server's CapabilityStatement, ensuring
   * our API's documentation is always in sync with its actual capabilities.
   * @Column({ nullable: true }) indicates that this column can be empty in the database.
   */
  @Column({ nullable: true })
  description: string;
}